const lowercaseToCamelcaseEventHandlersNameMap = new Map<string, Map<string, string>>([
  [
    'Element',
    new Map<keyof Element, string>([
      ['onfullscreenchange', 'onFullscreenChange'],
      ['onfullscreenerror', 'onFullscreenError'],
    ]),
  ],
  [
    'GlobalEventHandlers',
    new Map<keyof GlobalEventHandlers, string>([
      ['onabort', 'onAbort'],
      ['onanimationcancel', 'onAnimationCancel'],
      ['onanimationend', 'onAnimationEnd'],
      ['onanimationiteration', 'onAnimationIteration'],
      ['onanimationstart', 'onAnimationStart'],
      ['onauxclick', 'onAuxClick'],
      ['onbeforeinput', 'onBeforeInput'],
      ['onbeforematch', 'onBeforeMatch'],
      ['onbeforetoggle', 'onBeforeToggle'],
      ['onblur', 'onBlur'],
      ['oncancel', 'onCancel'],
      ['oncanplay', 'onCanPlay'],
      ['oncanplaythrough', 'onCanPlayThrough'],
      ['onchange', 'onChange'],
      ['onclick', 'onClick'],
      ['onclose', 'onClose'],
      ['oncontextlost', 'onContextLost'],
      ['oncontextmenu', 'onContextMenu'],
      ['oncontextrestored', 'onContextRestored'],
      ['oncopy', 'onCopy'],
      ['oncuechange', 'onCueChange'],
      ['oncut', 'onCut'],
      ['ondblclick', 'onDblClick'],
      ['ondrag', 'onDrag'],
      ['ondragend', 'onDragEnd'],
      ['ondragenter', 'onDragEnter'],
      ['ondragleave', 'onDragLeave'],
      ['ondragover', 'onDragOver'],
      ['ondragstart', 'onDragStart'],
      ['ondrop', 'onDrop'],
      ['ondurationchange', 'onDurationChange'],
      ['onemptied', 'onEmptied'],
      ['onended', 'onEnded'],
      ['onerror', 'onError'],
      ['onfocus', 'onFocus'],
      ['onformdata', 'onFormData'],
      ['ongotpointercapture', 'onGotPointerCapture'],
      ['oninput', 'onInput'],
      ['oninvalid', 'onInvalid'],
      ['onkeydown', 'onKeyDown'],
      ['onkeypress', 'onKeyPress'],
      ['onkeyup', 'onKeyUp'],
      ['onload', 'onLoad'],
      ['onloadeddata', 'onLoadedData'],
      ['onloadedmetadata', 'onLoadedMetadata'],
      ['onloadstart', 'onLoadStart'],
      ['onlostpointercapture', 'onLostPointerCapture'],
      ['onmousedown', 'onMouseDown'],
      ['onmouseenter', 'onMouseEnter'],
      ['onmouseleave', 'onMouseLeave'],
      ['onmousemove', 'onMouseMove'],
      ['onmouseout', 'onMouseOut'],
      ['onmouseover', 'onMouseOver'],
      ['onmouseup', 'onMouseUp'],
      ['onpaste', 'onPaste'],
      ['onpause', 'onPause'],
      ['onplay', 'onPlay'],
      ['onplaying', 'onPlaying'],
      ['onpointercancel', 'onPointerCancel'],
      ['onpointerdown', 'onPointerDown'],
      ['onpointerenter', 'onPointerEnter'],
      ['onpointerleave', 'onPointerLeave'],
      ['onpointermove', 'onPointerMove'],
      ['onpointerout', 'onPointerOut'],
      ['onpointerover', 'onPointerOver'],
      ['onpointerrawupdate', 'onPointerRawUpdate'],
      ['onpointerup', 'onPointerUp'],
      ['onprogress', 'onProgress'],
      ['onratechange', 'onRateChange'],
      ['onreset', 'onReset'],
      ['onresize', 'onResize'],
      ['onscroll', 'onScroll'],
      ['onscrollend', 'onScrollEnd'],
      ['onsecuritypolicyviolation', 'onSecurityPolicyViolation'],
      ['onseeked', 'onSeeked'],
      ['onseeking', 'onSeeking'],
      ['onselect', 'onSelect'],
      ['onselectionchange', 'onSelectionChange'],
      ['onselectstart', 'onSelectStart'],
      ['onslotchange', 'onSlotChange'],
      ['onstalled', 'onStalled'],
      ['onsubmit', 'onSubmit'],
      ['onsuspend', 'onSuspend'],
      ['ontimeupdate', 'onTimeUpdate'],
      ['ontoggle', 'onToggle'],
      ['ontouchcancel', 'onTouchCancel'],
      ['ontouchend', 'onTouchEnd'],
      ['ontouchmove', 'onTouchMove'],
      ['ontouchstart', 'onTouchStart'],
      ['ontransitioncancel', 'onTransitionCancel'],
      ['ontransitionend', 'onTransitionEnd'],
      ['ontransitionrun', 'onTransitionRun'],
      ['ontransitionstart', 'onTransitionStart'],
      ['onvolumechange', 'onVolumeChange'],
      ['onwaiting', 'onWaiting'],
      ['onwebkitanimationend', 'onWebkitAnimationEnd'],
      ['onwebkitanimationiteration', 'onWebkitAnimationIteration'],
      ['onwebkitanimationstart', 'onWebkitAnimationStart'],
      ['onwebkittransitionend', 'onWebkitTransitionEnd'],
      ['onwheel', 'onWheel'],
    ]),
  ],
  [
    'HTMLMediaElement',
    new Map<keyof HTMLMediaElement, string>([
      ['onencrypted', 'onEncrypted'],
      ['onwaitingforkey', 'onWaitingForKey'],
    ]),
  ],
  [
    'WindowEventHandlers',
    new Map<keyof WindowEventHandlers, string>([
      ['onafterprint', 'onAfterPrint'],
      ['onbeforeprint', 'onBeforePrint'],
      ['onbeforeunload', 'onBeforeUnload'],
      ['ongamepadconnected', 'onGamepadConnected'],
      ['ongamepaddisconnected', 'onGamepadDisconnected'],
      ['onhashchange', 'onHashChange'],
      ['onlanguagechange', 'onLanguageChange'],
      ['onmessage', 'onMessage'],
      ['onmessageerror', 'onMessageError'],
      ['onoffline', 'onOffline'],
      ['ononline', 'onOnline'],
      ['onpagehide', 'onPageHide'],
      ['onpagereveal', 'onPageReveal'],
      ['onpageshow', 'onPageShow'],
      ['onpageswap', 'onPageSwap'],
      ['onpopstate', 'onPopState'],
      ['onrejectionhandled', 'onRejectionHandled'],
      ['onstorage', 'onStorage'],
      ['onunhandledrejection', 'onUnhandledRejection'],
      ['onunload', 'onUnload'],
    ]),
  ],
  [
    'HTMLVideoElement',
    new Map<keyof HTMLVideoElement, string>([
      ['onenterpictureinpicture', 'onEnterPictureInPicture'],
      ['onleavepictureinpicture', 'onLeavePictureInPicture'],
    ]),
  ],
])

export function getCamelcaseEventHandlerName(
  elementInterfaceName: string,
  lowercaseEventHandlerName: string,
): string | undefined {
  return lowercaseToCamelcaseEventHandlersNameMap.get(elementInterfaceName)?.get(lowercaseEventHandlerName)
}